name = "PileResponse"
uuid = "e65c56c3-5d0d-4985-9588-0dd1a03c1526"
authors = ["Antony Orton"]
version = "1.0.0-DEV"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"

[compat]
DataInterpolations = "7.2.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
